// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtcvfdkhdlbrtxqwrngj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Y3ZmZGtoZGxicnR4cXdybmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDE1NDAsImV4cCI6MjA2ODk3NzU0MH0.NM2g51oxkhwi6GOv9Dt9PGRqNWicTCm9lvu8gAT2s7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});